// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	config "github.com/goran-ethernal/ChainIndexor/pkg/config"
	indexer "github.com/goran-ethernal/ChainIndexor/pkg/indexer"

	logger "github.com/goran-ethernal/ChainIndexor/internal/logger"

	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

type Factory_Expecter struct {
	mock *mock.Mock
}

func (_m *Factory) EXPECT() *Factory_Expecter {
	return &Factory_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: cfg, log
func (_m *Factory) Execute(cfg config.IndexerConfig, log *logger.Logger) (indexer.Indexer, error) {
	ret := _m.Called(cfg, log)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 indexer.Indexer
	var r1 error
	if rf, ok := ret.Get(0).(func(config.IndexerConfig, *logger.Logger) (indexer.Indexer, error)); ok {
		return rf(cfg, log)
	}
	if rf, ok := ret.Get(0).(func(config.IndexerConfig, *logger.Logger) indexer.Indexer); ok {
		r0 = rf(cfg, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(indexer.Indexer)
		}
	}

	if rf, ok := ret.Get(1).(func(config.IndexerConfig, *logger.Logger) error); ok {
		r1 = rf(cfg, log)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Factory_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Factory_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - cfg config.IndexerConfig
//   - log *logger.Logger
func (_e *Factory_Expecter) Execute(cfg interface{}, log interface{}) *Factory_Execute_Call {
	return &Factory_Execute_Call{Call: _e.mock.On("Execute", cfg, log)}
}

func (_c *Factory_Execute_Call) Run(run func(cfg config.IndexerConfig, log *logger.Logger)) *Factory_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.IndexerConfig), args[1].(*logger.Logger))
	})
	return _c
}

func (_c *Factory_Execute_Call) Return(_a0 indexer.Indexer, _a1 error) *Factory_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Factory_Execute_Call) RunAndReturn(run func(config.IndexerConfig, *logger.Logger) (indexer.Indexer, error)) *Factory_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	mock := &Factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
