// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check the health status of the API and all registered indexers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "API and indexer health status",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/indexers": {
            "get": {
                "description": "Get a list of all registered indexers with their event types and available endpoints",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexers"
                ],
                "summary": "List all indexers",
                "responses": {
                    "200": {
                        "description": "List of indexers",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.IndexerInfo"
                            }
                        }
                    }
                }
            }
        },
        "/indexers/{name}/events": {
            "get": {
                "description": "Retrieve events from a specific indexer with optional filtering, pagination, and sorting",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Get events from an indexer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Indexer name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event type to filter by",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum number of events to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of events to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter events from this block number",
                        "name": "from_block",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter events up to this block number",
                        "name": "to_block",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by address (contract or participant)",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort order: asc or desc",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of events with pagination info",
                        "schema": {
                            "$ref": "#/definitions/api.EventResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Indexer not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/indexers/{name}/events/timeseries": {
            "get": {
                "description": "Retrieve events aggregated by time periods (hour, day, or week) with event counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Get timeseries event data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Indexer name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "hour",
                            "day",
                            "week"
                        ],
                        "type": "string",
                        "default": "day",
                        "description": "Time period interval",
                        "name": "interval",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by specific event type",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter events from this block number",
                        "name": "from_block",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter events up to this block number",
                        "name": "to_block",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Timeseries data points with event counts",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.TimeseriesDataPoint"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Indexer not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/indexers/{name}/metrics": {
            "get": {
                "description": "Retrieve performance and processing metrics for a specific indexer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get indexer metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Indexer name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Indexer metrics",
                        "schema": {
                            "$ref": "#/definitions/api.MetricsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Indexer not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/indexers/{name}/stats": {
            "get": {
                "description": "Retrieve statistics and status information for a specific indexer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Get indexer statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Indexer name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Indexer statistics",
                        "schema": {
                            "$ref": "#/definitions/api.StatsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Indexer not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "description": "Standard error response format",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.EventResponse": {
            "description": "Response containing events and pagination information",
            "type": "object",
            "properties": {
                "events": {},
                "pagination": {
                    "$ref": "#/definitions/api.PaginationResult"
                }
            }
        },
        "api.HealthResponse": {
            "description": "Health status of the API and all indexers",
            "type": "object",
            "properties": {
                "indexers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.IndexerStatus"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.IndexerInfo": {
            "description": "Metadata about an available indexer",
            "type": "object",
            "properties": {
                "endpoints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "event_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.IndexerStatus": {
            "description": "Status information for a single indexer",
            "type": "object",
            "properties": {
                "event_count": {
                    "type": "integer",
                    "example": 150000
                },
                "healthy": {
                    "type": "boolean",
                    "example": true
                },
                "latest_block": {
                    "type": "integer",
                    "example": 19500000
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.MetricsResponse": {
            "description": "Performance metrics for an indexer",
            "type": "object",
            "properties": {
                "avg_events_per_day": {
                    "type": "number",
                    "example": 1250.5
                },
                "events_per_block": {
                    "type": "number",
                    "example": 12.5
                },
                "recent_blocks_analyzed": {
                    "type": "integer",
                    "example": 1000
                },
                "recent_events_count": {
                    "type": "integer",
                    "example": 12500
                }
            }
        },
        "api.PaginationResult": {
            "description": "Pagination information for paginated responses",
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "limit": {
                    "type": "integer",
                    "example": 100
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 1000
                }
            }
        },
        "api.StatsResponse": {
            "description": "Statistics and status information for an indexer",
            "type": "object",
            "properties": {
                "earliest_block": {
                    "type": "integer",
                    "example": 19000000
                },
                "event_counts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "latest_block": {
                    "type": "integer",
                    "example": 19500000
                },
                "total_events": {
                    "type": "integer",
                    "example": 150000
                }
            }
        },
        "api.TimeseriesDataPoint": {
            "description": "A data point in a timeseries response",
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 1250
                },
                "event_type": {
                    "type": "string",
                    "example": "Transfer"
                },
                "max_block": {
                    "type": "integer",
                    "example": 19510000
                },
                "min_block": {
                    "type": "integer",
                    "example": 19500000
                },
                "period": {
                    "type": "string",
                    "example": "2024-01-15"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
