// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	ethereum "github.com/ethereum/go-ethereum"
	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// EthClient is an autogenerated mock type for the EthClient type
type EthClient struct {
	mock.Mock
}

type EthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *EthClient) EXPECT() *EthClient_Expecter {
	return &EthClient_Expecter{mock: &_m.Mock}
}

// BatchGetBlockHeaders provides a mock function with given fields: ctx, blockNums
func (_m *EthClient) BatchGetBlockHeaders(ctx context.Context, blockNums []uint64) ([]*types.Header, error) {
	ret := _m.Called(ctx, blockNums)

	if len(ret) == 0 {
		panic("no return value specified for BatchGetBlockHeaders")
	}

	var r0 []*types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*types.Header, error)); ok {
		return rf(ctx, blockNums)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*types.Header); ok {
		r0 = rf(ctx, blockNums)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, blockNums)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_BatchGetBlockHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchGetBlockHeaders'
type EthClient_BatchGetBlockHeaders_Call struct {
	*mock.Call
}

// BatchGetBlockHeaders is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNums []uint64
func (_e *EthClient_Expecter) BatchGetBlockHeaders(ctx interface{}, blockNums interface{}) *EthClient_BatchGetBlockHeaders_Call {
	return &EthClient_BatchGetBlockHeaders_Call{Call: _e.mock.On("BatchGetBlockHeaders", ctx, blockNums)}
}

func (_c *EthClient_BatchGetBlockHeaders_Call) Run(run func(ctx context.Context, blockNums []uint64)) *EthClient_BatchGetBlockHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *EthClient_BatchGetBlockHeaders_Call) Return(_a0 []*types.Header, _a1 error) *EthClient_BatchGetBlockHeaders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_BatchGetBlockHeaders_Call) RunAndReturn(run func(context.Context, []uint64) ([]*types.Header, error)) *EthClient_BatchGetBlockHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// BatchGetLogs provides a mock function with given fields: ctx, queries
func (_m *EthClient) BatchGetLogs(ctx context.Context, queries []ethereum.FilterQuery) ([][]types.Log, error) {
	ret := _m.Called(ctx, queries)

	if len(ret) == 0 {
		panic("no return value specified for BatchGetLogs")
	}

	var r0 [][]types.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []ethereum.FilterQuery) ([][]types.Log, error)); ok {
		return rf(ctx, queries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []ethereum.FilterQuery) [][]types.Log); ok {
		r0 = rf(ctx, queries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]types.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []ethereum.FilterQuery) error); ok {
		r1 = rf(ctx, queries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_BatchGetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchGetLogs'
type EthClient_BatchGetLogs_Call struct {
	*mock.Call
}

// BatchGetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - queries []ethereum.FilterQuery
func (_e *EthClient_Expecter) BatchGetLogs(ctx interface{}, queries interface{}) *EthClient_BatchGetLogs_Call {
	return &EthClient_BatchGetLogs_Call{Call: _e.mock.On("BatchGetLogs", ctx, queries)}
}

func (_c *EthClient_BatchGetLogs_Call) Run(run func(ctx context.Context, queries []ethereum.FilterQuery)) *EthClient_BatchGetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]ethereum.FilterQuery))
	})
	return _c
}

func (_c *EthClient_BatchGetLogs_Call) Return(_a0 [][]types.Log, _a1 error) *EthClient_BatchGetLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_BatchGetLogs_Call) RunAndReturn(run func(context.Context, []ethereum.FilterQuery) ([][]types.Log, error)) *EthClient_BatchGetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *EthClient) Close() {
	_m.Called()
}

// EthClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type EthClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *EthClient_Expecter) Close() *EthClient_Close_Call {
	return &EthClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *EthClient_Close_Call) Run(run func()) *EthClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EthClient_Close_Call) Return() *EthClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *EthClient_Close_Call) RunAndReturn(run func()) *EthClient_Close_Call {
	_c.Run(run)
	return _c
}

// GetBlockHeader provides a mock function with given fields: ctx, blockNum
func (_m *EthClient) GetBlockHeader(ctx context.Context, blockNum uint64) (*types.Header, error) {
	ret := _m.Called(ctx, blockNum)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockHeader")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*types.Header, error)); ok {
		return rf(ctx, blockNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *types.Header); ok {
		r0 = rf(ctx, blockNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, blockNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_GetBlockHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockHeader'
type EthClient_GetBlockHeader_Call struct {
	*mock.Call
}

// GetBlockHeader is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNum uint64
func (_e *EthClient_Expecter) GetBlockHeader(ctx interface{}, blockNum interface{}) *EthClient_GetBlockHeader_Call {
	return &EthClient_GetBlockHeader_Call{Call: _e.mock.On("GetBlockHeader", ctx, blockNum)}
}

func (_c *EthClient_GetBlockHeader_Call) Run(run func(ctx context.Context, blockNum uint64)) *EthClient_GetBlockHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *EthClient_GetBlockHeader_Call) Return(_a0 *types.Header, _a1 error) *EthClient_GetBlockHeader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_GetBlockHeader_Call) RunAndReturn(run func(context.Context, uint64) (*types.Header, error)) *EthClient_GetBlockHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetFinalizedBlockHeader provides a mock function with given fields: ctx
func (_m *EthClient) GetFinalizedBlockHeader(ctx context.Context) (*types.Header, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFinalizedBlockHeader")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*types.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *types.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_GetFinalizedBlockHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFinalizedBlockHeader'
type EthClient_GetFinalizedBlockHeader_Call struct {
	*mock.Call
}

// GetFinalizedBlockHeader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EthClient_Expecter) GetFinalizedBlockHeader(ctx interface{}) *EthClient_GetFinalizedBlockHeader_Call {
	return &EthClient_GetFinalizedBlockHeader_Call{Call: _e.mock.On("GetFinalizedBlockHeader", ctx)}
}

func (_c *EthClient_GetFinalizedBlockHeader_Call) Run(run func(ctx context.Context)) *EthClient_GetFinalizedBlockHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EthClient_GetFinalizedBlockHeader_Call) Return(_a0 *types.Header, _a1 error) *EthClient_GetFinalizedBlockHeader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_GetFinalizedBlockHeader_Call) RunAndReturn(run func(context.Context) (*types.Header, error)) *EthClient_GetFinalizedBlockHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlockHeader provides a mock function with given fields: ctx
func (_m *EthClient) GetLatestBlockHeader(ctx context.Context) (*types.Header, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlockHeader")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*types.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *types.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_GetLatestBlockHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlockHeader'
type EthClient_GetLatestBlockHeader_Call struct {
	*mock.Call
}

// GetLatestBlockHeader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EthClient_Expecter) GetLatestBlockHeader(ctx interface{}) *EthClient_GetLatestBlockHeader_Call {
	return &EthClient_GetLatestBlockHeader_Call{Call: _e.mock.On("GetLatestBlockHeader", ctx)}
}

func (_c *EthClient_GetLatestBlockHeader_Call) Run(run func(ctx context.Context)) *EthClient_GetLatestBlockHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EthClient_GetLatestBlockHeader_Call) Return(_a0 *types.Header, _a1 error) *EthClient_GetLatestBlockHeader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_GetLatestBlockHeader_Call) RunAndReturn(run func(context.Context) (*types.Header, error)) *EthClient_GetLatestBlockHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function with given fields: ctx, query
func (_m *EthClient) GetLogs(ctx context.Context, query ethereum.FilterQuery) ([]types.Log, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []types.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) ([]types.Log, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) []types.Log); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ethereum.FilterQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type EthClient_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - query ethereum.FilterQuery
func (_e *EthClient_Expecter) GetLogs(ctx interface{}, query interface{}) *EthClient_GetLogs_Call {
	return &EthClient_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, query)}
}

func (_c *EthClient_GetLogs_Call) Run(run func(ctx context.Context, query ethereum.FilterQuery)) *EthClient_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ethereum.FilterQuery))
	})
	return _c
}

func (_c *EthClient_GetLogs_Call) Return(_a0 []types.Log, _a1 error) *EthClient_GetLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_GetLogs_Call) RunAndReturn(run func(context.Context, ethereum.FilterQuery) ([]types.Log, error)) *EthClient_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSafeBlockHeader provides a mock function with given fields: ctx
func (_m *EthClient) GetSafeBlockHeader(ctx context.Context) (*types.Header, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSafeBlockHeader")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*types.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *types.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthClient_GetSafeBlockHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSafeBlockHeader'
type EthClient_GetSafeBlockHeader_Call struct {
	*mock.Call
}

// GetSafeBlockHeader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EthClient_Expecter) GetSafeBlockHeader(ctx interface{}) *EthClient_GetSafeBlockHeader_Call {
	return &EthClient_GetSafeBlockHeader_Call{Call: _e.mock.On("GetSafeBlockHeader", ctx)}
}

func (_c *EthClient_GetSafeBlockHeader_Call) Run(run func(ctx context.Context)) *EthClient_GetSafeBlockHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EthClient_GetSafeBlockHeader_Call) Return(_a0 *types.Header, _a1 error) *EthClient_GetSafeBlockHeader_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthClient_GetSafeBlockHeader_Call) RunAndReturn(run func(context.Context) (*types.Header, error)) *EthClient_GetSafeBlockHeader_Call {
	_c.Call.Return(run)
	return _c
}

// NewEthClient creates a new instance of EthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthClient {
	mock := &EthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
