// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	indexer "github.com/goran-ethernal/ChainIndexor/pkg/indexer"
	mock "github.com/stretchr/testify/mock"
)

// Queryable is an autogenerated mock type for the Queryable type
type Queryable struct {
	mock.Mock
}

type Queryable_Expecter struct {
	mock *mock.Mock
}

func (_m *Queryable) EXPECT() *Queryable_Expecter {
	return &Queryable_Expecter{mock: &_m.Mock}
}

// GetEventTypes provides a mock function with no fields
func (_m *Queryable) GetEventTypes() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEventTypes")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Queryable_GetEventTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventTypes'
type Queryable_GetEventTypes_Call struct {
	*mock.Call
}

// GetEventTypes is a helper method to define mock.On call
func (_e *Queryable_Expecter) GetEventTypes() *Queryable_GetEventTypes_Call {
	return &Queryable_GetEventTypes_Call{Call: _e.mock.On("GetEventTypes")}
}

func (_c *Queryable_GetEventTypes_Call) Run(run func()) *Queryable_GetEventTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queryable_GetEventTypes_Call) Return(_a0 []string) *Queryable_GetEventTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Queryable_GetEventTypes_Call) RunAndReturn(run func() []string) *Queryable_GetEventTypes_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx
func (_m *Queryable) GetStats(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Queryable_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type Queryable_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queryable_Expecter) GetStats(ctx interface{}) *Queryable_GetStats_Call {
	return &Queryable_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *Queryable_GetStats_Call) Run(run func(ctx context.Context)) *Queryable_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Queryable_GetStats_Call) Return(_a0 interface{}, _a1 error) *Queryable_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Queryable_GetStats_Call) RunAndReturn(run func(context.Context) (interface{}, error)) *Queryable_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// QueryEvents provides a mock function with given fields: ctx, params
func (_m *Queryable) QueryEvents(ctx context.Context, params indexer.QueryParams) (interface{}, int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for QueryEvents")
	}

	var r0 interface{}
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, indexer.QueryParams) (interface{}, int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, indexer.QueryParams) interface{}); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, indexer.QueryParams) int); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, indexer.QueryParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Queryable_QueryEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryEvents'
type Queryable_QueryEvents_Call struct {
	*mock.Call
}

// QueryEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - params indexer.QueryParams
func (_e *Queryable_Expecter) QueryEvents(ctx interface{}, params interface{}) *Queryable_QueryEvents_Call {
	return &Queryable_QueryEvents_Call{Call: _e.mock.On("QueryEvents", ctx, params)}
}

func (_c *Queryable_QueryEvents_Call) Run(run func(ctx context.Context, params indexer.QueryParams)) *Queryable_QueryEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(indexer.QueryParams))
	})
	return _c
}

func (_c *Queryable_QueryEvents_Call) Return(_a0 interface{}, _a1 int, _a2 error) *Queryable_QueryEvents_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Queryable_QueryEvents_Call) RunAndReturn(run func(context.Context, indexer.QueryParams) (interface{}, int, error)) *Queryable_QueryEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueryable creates a new instance of Queryable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Queryable {
	mock := &Queryable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
