// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// Indexer is an autogenerated mock type for the Indexer type
type Indexer struct {
	mock.Mock
}

type Indexer_Expecter struct {
	mock *mock.Mock
}

func (_m *Indexer) EXPECT() *Indexer_Expecter {
	return &Indexer_Expecter{mock: &_m.Mock}
}

// EventsToIndex provides a mock function with no fields
func (_m *Indexer) EventsToIndex() map[common.Address]map[common.Hash]struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventsToIndex")
	}

	var r0 map[common.Address]map[common.Hash]struct{}
	if rf, ok := ret.Get(0).(func() map[common.Address]map[common.Hash]struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[common.Address]map[common.Hash]struct{})
		}
	}

	return r0
}

// Indexer_EventsToIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsToIndex'
type Indexer_EventsToIndex_Call struct {
	*mock.Call
}

// EventsToIndex is a helper method to define mock.On call
func (_e *Indexer_Expecter) EventsToIndex() *Indexer_EventsToIndex_Call {
	return &Indexer_EventsToIndex_Call{Call: _e.mock.On("EventsToIndex")}
}

func (_c *Indexer_EventsToIndex_Call) Run(run func()) *Indexer_EventsToIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Indexer_EventsToIndex_Call) Return(_a0 map[common.Address]map[common.Hash]struct{}) *Indexer_EventsToIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Indexer_EventsToIndex_Call) RunAndReturn(run func() map[common.Address]map[common.Hash]struct{}) *Indexer_EventsToIndex_Call {
	_c.Call.Return(run)
	return _c
}

// HandleLogs provides a mock function with given fields: logs
func (_m *Indexer) HandleLogs(logs []types.Log) error {
	ret := _m.Called(logs)

	if len(ret) == 0 {
		panic("no return value specified for HandleLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]types.Log) error); ok {
		r0 = rf(logs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Indexer_HandleLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleLogs'
type Indexer_HandleLogs_Call struct {
	*mock.Call
}

// HandleLogs is a helper method to define mock.On call
//   - logs []types.Log
func (_e *Indexer_Expecter) HandleLogs(logs interface{}) *Indexer_HandleLogs_Call {
	return &Indexer_HandleLogs_Call{Call: _e.mock.On("HandleLogs", logs)}
}

func (_c *Indexer_HandleLogs_Call) Run(run func(logs []types.Log)) *Indexer_HandleLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]types.Log))
	})
	return _c
}

func (_c *Indexer_HandleLogs_Call) Return(_a0 error) *Indexer_HandleLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Indexer_HandleLogs_Call) RunAndReturn(run func([]types.Log) error) *Indexer_HandleLogs_Call {
	_c.Call.Return(run)
	return _c
}

// HandleReorg provides a mock function with given fields: blockNum
func (_m *Indexer) HandleReorg(blockNum uint64) error {
	ret := _m.Called(blockNum)

	if len(ret) == 0 {
		panic("no return value specified for HandleReorg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(blockNum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Indexer_HandleReorg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleReorg'
type Indexer_HandleReorg_Call struct {
	*mock.Call
}

// HandleReorg is a helper method to define mock.On call
//   - blockNum uint64
func (_e *Indexer_Expecter) HandleReorg(blockNum interface{}) *Indexer_HandleReorg_Call {
	return &Indexer_HandleReorg_Call{Call: _e.mock.On("HandleReorg", blockNum)}
}

func (_c *Indexer_HandleReorg_Call) Run(run func(blockNum uint64)) *Indexer_HandleReorg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *Indexer_HandleReorg_Call) Return(_a0 error) *Indexer_HandleReorg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Indexer_HandleReorg_Call) RunAndReturn(run func(uint64) error) *Indexer_HandleReorg_Call {
	_c.Call.Return(run)
	return _c
}

// StartBlock provides a mock function with no fields
func (_m *Indexer) StartBlock() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartBlock")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// Indexer_StartBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartBlock'
type Indexer_StartBlock_Call struct {
	*mock.Call
}

// StartBlock is a helper method to define mock.On call
func (_e *Indexer_Expecter) StartBlock() *Indexer_StartBlock_Call {
	return &Indexer_StartBlock_Call{Call: _e.mock.On("StartBlock")}
}

func (_c *Indexer_StartBlock_Call) Run(run func()) *Indexer_StartBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Indexer_StartBlock_Call) Return(_a0 uint64) *Indexer_StartBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Indexer_StartBlock_Call) RunAndReturn(run func() uint64) *Indexer_StartBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewIndexer creates a new instance of Indexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Indexer {
	mock := &Indexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
