// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	store "github.com/goran-ethernal/ChainIndexor/pkg/fetcher/store"

	types "github.com/ethereum/go-ethereum/core/types"
)

// LogStore is an autogenerated mock type for the LogStore type
type LogStore struct {
	mock.Mock
}

type LogStore_Expecter struct {
	mock *mock.Mock
}

func (_m *LogStore) EXPECT() *LogStore_Expecter {
	return &LogStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *LogStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type LogStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *LogStore_Expecter) Close() *LogStore_Close_Call {
	return &LogStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *LogStore_Close_Call) Run(run func()) *LogStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LogStore_Close_Call) Return(_a0 error) *LogStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogStore_Close_Call) RunAndReturn(run func() error) *LogStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function with given fields: ctx, address, fromBlock, toBlock
func (_m *LogStore) GetLogs(ctx context.Context, address common.Address, fromBlock uint64, toBlock uint64) ([]types.Log, []store.CoverageRange, error) {
	ret := _m.Called(ctx, address, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []types.Log
	var r1 []store.CoverageRange
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint64, uint64) ([]types.Log, []store.CoverageRange, error)); ok {
		return rf(ctx, address, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, uint64, uint64) []types.Log); ok {
		r0 = rf(ctx, address, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, uint64, uint64) []store.CoverageRange); ok {
		r1 = rf(ctx, address, fromBlock, toBlock)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]store.CoverageRange)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.Address, uint64, uint64) error); ok {
		r2 = rf(ctx, address, fromBlock, toBlock)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LogStore_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type LogStore_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - address common.Address
//   - fromBlock uint64
//   - toBlock uint64
func (_e *LogStore_Expecter) GetLogs(ctx interface{}, address interface{}, fromBlock interface{}, toBlock interface{}) *LogStore_GetLogs_Call {
	return &LogStore_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, address, fromBlock, toBlock)}
}

func (_c *LogStore_GetLogs_Call) Run(run func(ctx context.Context, address common.Address, fromBlock uint64, toBlock uint64)) *LogStore_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(uint64), args[3].(uint64))
	})
	return _c
}

func (_c *LogStore_GetLogs_Call) Return(logs []types.Log, coverage []store.CoverageRange, err error) *LogStore_GetLogs_Call {
	_c.Call.Return(logs, coverage, err)
	return _c
}

func (_c *LogStore_GetLogs_Call) RunAndReturn(run func(context.Context, common.Address, uint64, uint64) ([]types.Log, []store.CoverageRange, error)) *LogStore_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnsyncedTopics provides a mock function with given fields: ctx, addresses, topics, upToBlock
func (_m *LogStore) GetUnsyncedTopics(ctx context.Context, addresses []common.Address, topics [][]common.Hash, upToBlock uint64) (*store.UnsyncedTopics, error) {
	ret := _m.Called(ctx, addresses, topics, upToBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetUnsyncedTopics")
	}

	var r0 *store.UnsyncedTopics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []common.Address, [][]common.Hash, uint64) (*store.UnsyncedTopics, error)); ok {
		return rf(ctx, addresses, topics, upToBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []common.Address, [][]common.Hash, uint64) *store.UnsyncedTopics); ok {
		r0 = rf(ctx, addresses, topics, upToBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.UnsyncedTopics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []common.Address, [][]common.Hash, uint64) error); ok {
		r1 = rf(ctx, addresses, topics, upToBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogStore_GetUnsyncedTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnsyncedTopics'
type LogStore_GetUnsyncedTopics_Call struct {
	*mock.Call
}

// GetUnsyncedTopics is a helper method to define mock.On call
//   - ctx context.Context
//   - addresses []common.Address
//   - topics [][]common.Hash
//   - upToBlock uint64
func (_e *LogStore_Expecter) GetUnsyncedTopics(ctx interface{}, addresses interface{}, topics interface{}, upToBlock interface{}) *LogStore_GetUnsyncedTopics_Call {
	return &LogStore_GetUnsyncedTopics_Call{Call: _e.mock.On("GetUnsyncedTopics", ctx, addresses, topics, upToBlock)}
}

func (_c *LogStore_GetUnsyncedTopics_Call) Run(run func(ctx context.Context, addresses []common.Address, topics [][]common.Hash, upToBlock uint64)) *LogStore_GetUnsyncedTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]common.Address), args[2].([][]common.Hash), args[3].(uint64))
	})
	return _c
}

func (_c *LogStore_GetUnsyncedTopics_Call) Return(_a0 *store.UnsyncedTopics, _a1 error) *LogStore_GetUnsyncedTopics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogStore_GetUnsyncedTopics_Call) RunAndReturn(run func(context.Context, []common.Address, [][]common.Hash, uint64) (*store.UnsyncedTopics, error)) *LogStore_GetUnsyncedTopics_Call {
	_c.Call.Return(run)
	return _c
}

// HandleReorg provides a mock function with given fields: ctx, fromBlock
func (_m *LogStore) HandleReorg(ctx context.Context, fromBlock uint64) error {
	ret := _m.Called(ctx, fromBlock)

	if len(ret) == 0 {
		panic("no return value specified for HandleReorg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, fromBlock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogStore_HandleReorg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleReorg'
type LogStore_HandleReorg_Call struct {
	*mock.Call
}

// HandleReorg is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock uint64
func (_e *LogStore_Expecter) HandleReorg(ctx interface{}, fromBlock interface{}) *LogStore_HandleReorg_Call {
	return &LogStore_HandleReorg_Call{Call: _e.mock.On("HandleReorg", ctx, fromBlock)}
}

func (_c *LogStore_HandleReorg_Call) Run(run func(ctx context.Context, fromBlock uint64)) *LogStore_HandleReorg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *LogStore_HandleReorg_Call) Return(_a0 error) *LogStore_HandleReorg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogStore_HandleReorg_Call) RunAndReturn(run func(context.Context, uint64) error) *LogStore_HandleReorg_Call {
	_c.Call.Return(run)
	return _c
}

// StoreLogs provides a mock function with given fields: ctx, addresses, topics, logs, fromBlock, toBlock
func (_m *LogStore) StoreLogs(ctx context.Context, addresses []common.Address, topics [][]common.Hash, logs []types.Log, fromBlock uint64, toBlock uint64) error {
	ret := _m.Called(ctx, addresses, topics, logs, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for StoreLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []common.Address, [][]common.Hash, []types.Log, uint64, uint64) error); ok {
		r0 = rf(ctx, addresses, topics, logs, fromBlock, toBlock)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogStore_StoreLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreLogs'
type LogStore_StoreLogs_Call struct {
	*mock.Call
}

// StoreLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - addresses []common.Address
//   - topics [][]common.Hash
//   - logs []types.Log
//   - fromBlock uint64
//   - toBlock uint64
func (_e *LogStore_Expecter) StoreLogs(ctx interface{}, addresses interface{}, topics interface{}, logs interface{}, fromBlock interface{}, toBlock interface{}) *LogStore_StoreLogs_Call {
	return &LogStore_StoreLogs_Call{Call: _e.mock.On("StoreLogs", ctx, addresses, topics, logs, fromBlock, toBlock)}
}

func (_c *LogStore_StoreLogs_Call) Run(run func(ctx context.Context, addresses []common.Address, topics [][]common.Hash, logs []types.Log, fromBlock uint64, toBlock uint64)) *LogStore_StoreLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]common.Address), args[2].([][]common.Hash), args[3].([]types.Log), args[4].(uint64), args[5].(uint64))
	})
	return _c
}

func (_c *LogStore_StoreLogs_Call) Return(_a0 error) *LogStore_StoreLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LogStore_StoreLogs_Call) RunAndReturn(run func(context.Context, []common.Address, [][]common.Hash, []types.Log, uint64, uint64) error) *LogStore_StoreLogs_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogStore creates a new instance of LogStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogStore {
	mock := &LogStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
