// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	indexer "github.com/goran-ethernal/ChainIndexor/pkg/indexer"
	mock "github.com/stretchr/testify/mock"
)

// IndexerRegistry is an autogenerated mock type for the IndexerRegistry type
type IndexerRegistry struct {
	mock.Mock
}

type IndexerRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *IndexerRegistry) EXPECT() *IndexerRegistry_Expecter {
	return &IndexerRegistry_Expecter{mock: &_m.Mock}
}

// GetByName provides a mock function with given fields: name
func (_m *IndexerRegistry) GetByName(name string) indexer.Indexer {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 indexer.Indexer
	if rf, ok := ret.Get(0).(func(string) indexer.Indexer); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(indexer.Indexer)
		}
	}

	return r0
}

// IndexerRegistry_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type IndexerRegistry_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - name string
func (_e *IndexerRegistry_Expecter) GetByName(name interface{}) *IndexerRegistry_GetByName_Call {
	return &IndexerRegistry_GetByName_Call{Call: _e.mock.On("GetByName", name)}
}

func (_c *IndexerRegistry_GetByName_Call) Run(run func(name string)) *IndexerRegistry_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IndexerRegistry_GetByName_Call) Return(_a0 indexer.Indexer) *IndexerRegistry_GetByName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IndexerRegistry_GetByName_Call) RunAndReturn(run func(string) indexer.Indexer) *IndexerRegistry_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with no fields
func (_m *IndexerRegistry) ListAll() []indexer.Indexer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []indexer.Indexer
	if rf, ok := ret.Get(0).(func() []indexer.Indexer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]indexer.Indexer)
		}
	}

	return r0
}

// IndexerRegistry_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type IndexerRegistry_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
func (_e *IndexerRegistry_Expecter) ListAll() *IndexerRegistry_ListAll_Call {
	return &IndexerRegistry_ListAll_Call{Call: _e.mock.On("ListAll")}
}

func (_c *IndexerRegistry_ListAll_Call) Run(run func()) *IndexerRegistry_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IndexerRegistry_ListAll_Call) Return(_a0 []indexer.Indexer) *IndexerRegistry_ListAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IndexerRegistry_ListAll_Call) RunAndReturn(run func() []indexer.Indexer) *IndexerRegistry_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewIndexerRegistry creates a new instance of IndexerRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIndexerRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IndexerRegistry {
	mock := &IndexerRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
