// Code generated by indexer-gen. DO NOT EDIT.
package erc20

import (
	"context"
	"reflect"

	"github.com/goran-ethernal/ChainIndexor/internal/indexer"
	pkgindexer "github.com/goran-ethernal/ChainIndexor/pkg/indexer"
)

// InitEventMetadata returns metadata for all indexed events.
func (idx *ERC20Indexer) InitEventMetadata() map[string]*indexer.EventMetadata {
	return map[string]*indexer.EventMetadata{
		"transfer": {
			Name:      "Transfer",
			Table:     "transfers",
			EventType: reflect.TypeOf((*Transfer)(nil)),
			AddressColumns: []string{
				"from_address",
				"to_address",
			},
		},
		"approval": {
			Name:      "Approval",
			Table:     "approvals",
			EventType: reflect.TypeOf((*Approval)(nil)),
			AddressColumns: []string{
				"owner_address",
				"spender_address",
			},
		},
	}
}

// Ensure ERC20Indexer implements pkgindexer.Queryable
var _ pkgindexer.Queryable = (*ERC20Indexer)(nil)

// QueryEvents retrieves events based on the provided query parameters.
func (idx *ERC20Indexer) QueryEvents(ctx context.Context, params pkgindexer.QueryParams) (any, int, error) {
	return idx.BaseIndexer.QueryEvents(ctx, idx, params)
}

// GetStats returns statistics about the indexed data.
func (idx *ERC20Indexer) GetStats(ctx context.Context) (pkgindexer.StatsResponse, error) {
	return idx.BaseIndexer.GetStats(ctx, idx)
}

// GetEventTypes returns the list of event type names this indexer handles.
func (idx *ERC20Indexer) GetEventTypes() []string {
	return idx.BaseIndexer.GetEventTypes(idx)
}

// QueryEventsTimeseries retrieves time-series aggregated event data.
func (idx *ERC20Indexer) QueryEventsTimeseries(ctx context.Context, params pkgindexer.TimeseriesParams) ([]pkgindexer.TimeseriesDataPoint, error) {
	return idx.BaseIndexer.QueryEventsTimeseries(ctx, idx, params)
}

// GetMetrics returns performance and processing metrics.
func (idx *ERC20Indexer) GetMetrics(ctx context.Context) (pkgindexer.MetricsResponse, error) {
	return idx.BaseIndexer.GetMetrics(ctx, idx)
}
