// Code generated by indexer-gen. DO NOT EDIT.
package erc20

import (
	"github.com/ethereum/go-ethereum/common"
)


// Transfer represents a Transfer event.
// Event signature: Transfer(address indexed from, address indexed to, uint256 value)
type Transfer struct {
	ID          int64       `meddler:"id,pk"`
	BlockNumber uint64      `meddler:"block_number"`
	BlockHash   common.Hash `meddler:"block_hash,hash"`
	TxHash      common.Hash `meddler:"tx_hash,hash"`
	TxIndex     uint        `meddler:"tx_index"`
	LogIndex    uint        `meddler:"log_index"`
	From common.Address `meddler:"from_address,address"`
	To common.Address `meddler:"to_address,address"`
	Value string `meddler:"value"`
}

// Approval represents a Approval event.
// Event signature: Approval(address indexed owner, address indexed spender, uint256 value)
type Approval struct {
	ID          int64       `meddler:"id,pk"`
	BlockNumber uint64      `meddler:"block_number"`
	BlockHash   common.Hash `meddler:"block_hash,hash"`
	TxHash      common.Hash `meddler:"tx_hash,hash"`
	TxIndex     uint        `meddler:"tx_index"`
	LogIndex    uint        `meddler:"log_index"`
	Owner common.Address `meddler:"owner_address,address"`
	Spender common.Address `meddler:"spender_address,address"`
	Value string `meddler:"value"`
}

