// Code generated by indexer-gen. DO NOT EDIT.
package erc20

import (
	"github.com/goran-ethernal/ChainIndexor/internal/logger"
	"github.com/goran-ethernal/ChainIndexor/pkg/config"
	"github.com/goran-ethernal/ChainIndexor/pkg/indexer"
)

func init() {
	indexer.Register("erc20", func(cfg config.IndexerConfig, log *logger.Logger) (indexer.Indexer, error) {
		return NewERC20Indexer(cfg, log)
	})
}
