// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// Detector is an autogenerated mock type for the Detector type
type Detector struct {
	mock.Mock
}

type Detector_Expecter struct {
	mock *mock.Mock
}

func (_m *Detector) EXPECT() *Detector_Expecter {
	return &Detector_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Detector) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Detector_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Detector_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Detector_Expecter) Close() *Detector_Close_Call {
	return &Detector_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Detector_Close_Call) Run(run func()) *Detector_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Detector_Close_Call) Return(_a0 error) *Detector_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Detector_Close_Call) RunAndReturn(run func() error) *Detector_Close_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAndRecordBlocks provides a mock function with given fields: ctx, logs, fromBlock, toBlock
func (_m *Detector) VerifyAndRecordBlocks(ctx context.Context, logs []types.Log, fromBlock uint64, toBlock uint64) ([]*types.Header, error) {
	ret := _m.Called(ctx, logs, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndRecordBlocks")
	}

	var r0 []*types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []types.Log, uint64, uint64) ([]*types.Header, error)); ok {
		return rf(ctx, logs, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []types.Log, uint64, uint64) []*types.Header); ok {
		r0 = rf(ctx, logs, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []types.Log, uint64, uint64) error); ok {
		r1 = rf(ctx, logs, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Detector_VerifyAndRecordBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAndRecordBlocks'
type Detector_VerifyAndRecordBlocks_Call struct {
	*mock.Call
}

// VerifyAndRecordBlocks is a helper method to define mock.On call
//   - ctx context.Context
//   - logs []types.Log
//   - fromBlock uint64
//   - toBlock uint64
func (_e *Detector_Expecter) VerifyAndRecordBlocks(ctx interface{}, logs interface{}, fromBlock interface{}, toBlock interface{}) *Detector_VerifyAndRecordBlocks_Call {
	return &Detector_VerifyAndRecordBlocks_Call{Call: _e.mock.On("VerifyAndRecordBlocks", ctx, logs, fromBlock, toBlock)}
}

func (_c *Detector_VerifyAndRecordBlocks_Call) Run(run func(ctx context.Context, logs []types.Log, fromBlock uint64, toBlock uint64)) *Detector_VerifyAndRecordBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]types.Log), args[2].(uint64), args[3].(uint64))
	})
	return _c
}

func (_c *Detector_VerifyAndRecordBlocks_Call) Return(_a0 []*types.Header, _a1 error) *Detector_VerifyAndRecordBlocks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Detector_VerifyAndRecordBlocks_Call) RunAndReturn(run func(context.Context, []types.Log, uint64, uint64) ([]*types.Header, error)) *Detector_VerifyAndRecordBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// NewDetector creates a new instance of Detector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Detector {
	mock := &Detector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
